### ISSUE TITLE
Crash when hitting certain item's with temporal pick.

### ISSUE THREAD

**Issue by 7bryce2** [Lumaceon/ClockworkPhase#13]
Added the mod to All the Mods 3 and whenever I hit certain items with the temporal pickaxe (Obsidian) it instantly crashes the game.

**Comment by 7bryce2** [comment]
Block of Quarts Crashes the game also. As well as mining to much netherack at once. Here's an attached crash report.
[Clockwork Crash.txt](https://github.com/Lumaceon/ClockworkPhase/files/2965207/Clockwork.Crash.txt)

**Comment by DoctorFTB** [comment]
Try 1.0c version.

**Comment by 7bryce2** [comment]
It's fixed for both Block of Quartz and Obsidian :D. Thanks a bunch.
