### ISSUE TITLE
Server crash - on placing a celestial compass.

### ISSUE THREAD

**Issue by ProsperCraft** [Lumaceon/ClockworkPhase#20]
ava.lang.NoClassDefFoundError: Could not initialize class lumaceon.mods.clockworkphase.custom.CustomEvents

https://gist.github.com/ProsperCraft/7c5fda6eb3fa2e25b78add7f0dd90f00

Modpack - DrTARDIS 2 - https://minecraft.curseforge.com/projects/drtardis-2-new-adventures

**Comment by ProsperCraft** [comment]
When the server came back up and the player logged back in - 
Crashed again.
https://gist.github.com/ProsperCraft/add1ee5f5a6bd34b1dc40394c6724b72

**Comment by ProsperCraft** [comment]
Server crashlooping - https://paste.fedoraproject.org/paste/V4chAXJd1YIg5yHawdqBwA

**Comment by DoctorFTB** [comment]
Try 1.0g version.
Added.

**Comment by ProsperCraft** [comment]
Fixed, thank you.
