### ISSUE TITLE
Pickaxe mines much slower after updating to 1.0d

### ISSUE THREAD

**Issue by Landstryder** [Lumaceon/ClockworkPhase#4]
After updating to from 1.0c to 1.0d (using Atonement pack) the shovel was fixed but the pickaxe became as useless as the shovel use to be. With a pickaxe with 360 quality and 405 speed and 480 memory the pick takes a full 3 seconds or more to break stone, cobble, bricks and over 10 seconds to break the winder.

**Comment by 1skandar** [comment]
Ok, to add some clarification: A brand new pickaxe in 1.0d mines vanilla stone and cobblestone plus all vanilla ores like it should. It mines Botania blocks, Thaumcraft blocks like it should. It is failing on Flaxbeard Steampower blocks, the Winding box from Clockwork Phase, and crafted vanilla blocks, like stone bricks.

**Comment by Lumaceon** [comment]
Thanks for the reports, this should be fixed in 1.0f (hopefully for good this time).
